# Generated by Django 3.1.7 on 2021-03-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=90, verbose_name='Title')),
                ('pic', models.CharField(db_index=True, max_length=90, verbose_name='Pic')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('is_swiper', models.BooleanField(default=False, verbose_name='Is Swiper')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
    ]
