# Generated by Django 3.1.7 on 2021-05-11 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='psy_type',
            field=models.ForeignKey(blank=True, db_column='psy_type', default=4, on_delete=django.db.models.deletion.PROTECT, to='app.category'),
        ),
    ]
