# Generated by Django 3.1.7 on 2021-03-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210327_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=90, verbose_name='Title')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Desc'),
        ),
    ]
