# Generated by Django 3.1.7 on 2021-03-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210329_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['create_date']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['create_date']},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['create_date']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['create_date']},
        ),
    ]
