# Generated by Django 3.1.7 on 2021-04-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='user_id',
        ),
        migrations.AddField(
            model_name='record',
            name='openid',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Open Id'),
        ),
    ]
